name: Extract
description: Extracts the filesystem from a Docker image
author: Forum One

requirements: [docker]

configuration:
  additionalProperties: false
  required: [from]
  properties:
    image:
      type: [string, object]
      additionalProperties: false
      properties:
        repository:
          type: string
        service:
          type: string
        tag:
          type: string
    from:
      type: string
    to:
      type: string
    pull:
      type: boolean
    verbose:
      type: boolean
    debug:
      type: boolean
