steps:
  - label: Lint
    plugins:
      - plugin-linter#v2.0.0:
          id: forumone/extract

  - label: Shellcheck
    plugins:
      - shellcheck#v1.1.2:
          files:
            - hooks/**
            - lib/**

  - label: Tests
    plugins:
      - docker-compose#v3.0.0:
          run: tests
